services:
  load_balancer:
    build: 
      context: ./load_balancer
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - load_balancer_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  server1:
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment:
      - SERVER_ID=1
    ports:
      - "5001:5000"
    networks:
      - load_balancer_network


  server2:
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment:
      - SERVER_ID=2
    ports:
      - "5002:5000"
    networks:
      - load_balancer_network

  server3:
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment:
      - SERVER_ID=3
    ports:
      - "5003:5000"
    networks:
      - load_balancer_network

networks:
  load_balancer_network:
    driver: bridge