version: '3'

services:
  sub-server-1:
    build:
      context: .
      args:
        SERVER_ID: 1
    ports:
      - "5001:5000"

  sub-server-2:
    build:
      context: .
      args:
        SERVER_ID: 2
    ports:
      - "5002:5000"

  sub-server-3:
    build:
      context: .
      args:
        SERVER_ID: 3
    ports:
      - "5003:5000"

  sub-server-4:
    build:
      context: .
      args:
        SERVER_ID: 4
    ports:
      - "5004:5000"
