services:
  load_balancer:
    build: 
      context: ./load_balancer
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - load_balancer_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs


networks:
  load_balancer_network:
    driver: bridge